/*
 * RobotNumInit.java
 *
 * Created on June 8, 2007, 7:05 PM
 */

package org.havalinasw.MGUI;

import java.awt.Container;
import javax.swing.JComponent;

/**
 *
 * @author  bhgray
 */
public class RobotNumInit extends javax.swing.JPanel {
    
    /** Creates new form RobotNumInit */
    public RobotNumInit() {
        initComponents();
        setName("InitRobotCard");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        robotInitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numRobotsSpinner = new javax.swing.JSpinner();
        robotInfoInitButton = new javax.swing.JButton();

        robotInitButton.setText("Initialize Robots");

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Number of Robots in Simulation (1 - 10):");
        add(jLabel1, new java.awt.GridBagConstraints());

        numRobotsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(numRobotsSpinner, gridBagConstraints);

        robotInfoInitButton.setBackground(java.awt.Color.white);
        robotInfoInitButton.setText("Initialize");
        robotInfoInitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                robotInfoInitButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(robotInfoInitButton, gridBagConstraints);

    }

    private void robotInfoInitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
       MRobotMain main = (MRobotMain)this.getRootPane().getParent();
       main.setupRobotInitPanels(); 
       
    }

    private void numRobotsSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numRobotsSpinnerStateChanged
    	MRobotMain main = (MRobotMain)this.getRootPane().getParent();
        
        if (MainFrame.DEBUG) {
            System.out.println(main);
        }
        
        MRobotMain.currentStatus = MRobotMain.Status.INIT;
 
    }//GEN-LAST:event_numRobotsSpinnerStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner numRobotsSpinner;
    private javax.swing.JButton robotInfoInitButton;
    private javax.swing.JButton robotInitButton;
    // End of variables declaration//GEN-END:variables
    
    public int getNumRobots() {
        return ((Integer)numRobotsSpinner.getValue()).intValue();
    }
}
